### ISSUE TITLE
missing requirements.txt

### ISSUE THREAD

**Issue by gudeh** [NYU-MLDA/OpenABC#1]
Hi there, I couldn't find the requirements file in your repository, as indicated by the README.

**Comment by gudeh** [comment]
Also, the link: https://archive.nyu.edu/handle/2451/63311, reads: "There are no files associated with this item.", I wasn't able to find any downladable file.

**Comment by animeshbchowdhury** [comment]
Hi @gudeh ,

Can you access the globus endpoint link mentioned in the updated abstract of https://archive.nyu.edu/handle/2451/63311? Since it's a large dataset of around 1.4TB, we are migrating the data to our university cloud service for better download speed.

Also,  I will update the requirements.txt file shortly.

**Comment by animeshbchowdhury** [comment]
Hi @gudeh ,

I have added the requirements.txt file. Let me know if you face any issue.

**Comment by gudeh** [comment]
I got the error: 
`gudeh@snwoflake:~/Desktop/OpenABC$ python3 -m pip install -r requirements.txt 
ERROR: Invalid requirement: 'absl-py=0.12.0=pyhd8ed1ab_0' (from line 1 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
`
I tried to modify it to: `absl-py=0.12.0==pyhd8ed1ab_0`.
Then it returned:
`gudeh@snwoflake:~/Desktop/OpenABC$ python3 -m pip install -r requirements.txt 
ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 1 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
`
Also inserting a "=" on this package it returned:
`gudeh@snwoflake:~/Desktop/OpenABC$ python3 -m pip install -r requirements.txt 
ERROR: Invalid requirement: '_libgcc_mutex=0.1==main' (from line 1 of requirements.txt)
`

**Comment by animeshbchowdhury** [comment]
Hi,

This is a setup for creating a conda environment. I would suggest to
install the packages independently if you're using virtualenv.

Best,
Animesh

**Comment by gudeh** [comment]
I see! As you may notice I use python directly installing it in my Linux. And I use pip to install packages. The command I tried usually does the trick with "requirements.txt" files from projects. 
I would suggest you to enable running the requirements without requiring conda or any other environment tool. 
I am really interested in using openroad and CGNs, I will have a look at your code.
I was able to access your dataset nonetheless. Great job!

**Comment by animeshbchowdhury** [comment]
Thanks for trying this OpenABC-D.

Sure, as part of our future enhancement plan, we will try supporting it
with normal virtualenv pipeline too!

I was reached out by other people that the dataset download speed is too
slow so we are working towards it.

Best,
Animesh
