### ISSUE TITLE
Can't use the ML-ready dataset

### ISSUE THREAD

**Issue by sparklesea** [NYU-MLDA/OpenABC#10]
Hi,
I follow the tutorial but I can't take the training and evaluation step:
1.the requirements.txt contains many libraries that cannot be installed, so I just use my own env. 
2.But the ML-ready dataset is too old, I can't create an environment(pytorch==1.7.0 can't be installed) to use it.
do you have a new ML-ready dataset generated by new version of pyG?
Best regards

**Comment by animeshbchowdhury** [comment]
Hi @sparklesea,

Unfortunately, I don't have a new ML-ready dataset compatible with PyG 2.0. Anything lesser than PyG < 2.0 should work.
There is an alternative if you want to re-use the ML-ready dataset with new PyG 2.0 version.

https://github.com/pyg-team/pytorch_geometric/discussions/4502

I do have a singularity container which have all the dependencies of requirements.txt installed. I can share that with you if needed.

Best regards,
Animesh

**Comment by sparklesea** [comment]
Thank you for your reply！ @animeshbchowdhury 
I already set up the environment to use the ML-ready dataset.  Meanwhile, the solution you shared works, so I can re-use the ML-ready dataset with PyG>2.0.
Thanks again!

**Comment by luarss** [comment]
Hi @animeshbchowdhury, could you share the container with me as well? Thanks.
