### ISSUE TITLE
Dataset for QoR prediction

### ISSUE THREAD

**Issue by ankursharma129** [NYU-MLDA/OpenABC#2]
Hi,

We want to use your dataset to do QoR predictions. We followed your README.md file and downloaded the 19GB dataset for ML. We extracted the .pt files and read them, but are struggling to make sense of the numbers. The excel image shows the data we extracted from synthesisStatistics.pickle. Can you tell us what the numbers for each design indicate? 

![image](https://user-images.githubusercontent.com/41720880/163693717-b6a70dbd-e228-417b-86b7-6aec2ef139c0.png)

The snippet below shows the data we got from the 'ac97_ctrl_syn706_step0.pt'. This data is below:
`
{'and_nodes': tensor(11464),
 'desName': ['ac97_ctrl'],
 'edge_index': tensor([[ 2339,  2340,  2340,  ..., 15938, 15938, 15939],
         [ 2338,     2,     3,  ...,  2336, 15932, 15938]]),
 'edge_type': tensor([1, 0, 1,  ..., 1, 0, 0]),
 'longest_path': tensor(11),
 'node_id': ['ys__n0',
  'ys__n1',
  'ys__n3',
  'ys__n4',
  'ys__n7',
  ...],
 'node_type': tensor([0, 0, 0,  ..., 1, 2, 1]),
 'not_edges': tensor(14326),
 'num_inverted_predecessors': tensor([0, 0, 0,  ..., 1, 1, 0]),
 'pi': tensor(2339),
 'po': tensor(2137),
 'stepID': [0],
 'synID': [706],
 'synVec': tensor([1, 4, 5, 6, 0, 3, 0, 1, 6, 1, 1, 4, 6, 1, 1, 3, 0, 1, 0, 5])}
`
Can you explain how do we get the timing numbers from the above?

We were wondering if we need to download the 1.4TB zipped files to generate the ML training and testing datasets, or is there a better way to go about this? Can you guide us on how to use the useful datapoints from the 1.4TB dataset without downloading it all? We are students of UC San Diego and trying to maximize our resource utilization.

Thank you!

**Comment by ankursharma129** [comment]
To be more precise, how do we find information about the delay from each design?

**Comment by animeshbchowdhury** [comment]
Hi Ankur,

The pytorch data points do not contain the target labels. The synthesisStats.pickle file contain the information. You can refer the file [here](https://github.com/NYU-MLDA/OpenABC/blob/master/datagen/utilities/pickleStatsForML.py) to understand more how the target data has been stored. In short, after applying 1500 synthesis recipes on each design, we collect graph statistics of final AIG and map it using nangate45nm.lib to get the area and delay from ABC. The synthesisStats.pickle is basically a dictionary, where for each design you will have five list. Each list contains 1500 entries. 

These five lists are ordered as follows: [ANDgates,NOTgates,lpLen,area,delay]

So, the first list contains information about number of nodes in the resulting AIG after applying the synthesis recipes. Entry k denotes the synthesis output after applying synthesis recipe k. The labels which you might be interested in looking are: lplen (Denotes longest path of AIG) and delay (Critical path delay of resultant AIG post techmapping).

The 19GB dataset is a part which was used for a specific downstream task: Given the initial unoptimized AIG, predict the number of nodes in the resultant AIG after application of a given synthesis recipe. If you want to predict longest path/delay, you do not need anything else. However, if you want to predict delay from final AIG (i.e. Given an AIG, predict delay post techmapping), you need to download the 1.4TB dataset.

**Comment by ankursharma129** [comment]
Hey Animesh,

Thanks for your prompt response. I think we understand how to navigate the dataset better now.

Cheers!

**Comment by animeshbchowdhury** [comment]
Great!
