### ISSUE TITLE
Zip file of initial AIG

### ISSUE THREAD

**Issue by lirui-shanghaitech** [NYU-MLDA/OpenABC#3]
The origin full dataset is too huge, we have trouble to download it. Since, we only want the the initial AIG file. We want to know, is there any zip file/link that only have the initial AIG files? Thanks.

**Comment by animeshbchowdhury** [comment]
Hi,

I've added initial AIG files as part of this repository. Please feel free to use them.

Best,
Animesh

**Comment by animeshbchowdhury** [comment]
@lirui-shanghaitech lemme know if you need anything else. I will close the issue.
