### ISSUE TITLE
Can't download dataset

### ISSUE THREAD

**Issue by ZFTurbo** [NYU-MLDA/OpenABC#5]
Hello. I'm trying to download dataset using link from README:
https://app.globus.org/file-manager?origin_id=ae7b03ad-9e50-472c-9601-ff99054ae47c&origin_path=%2F

I get the following error:
```
Authentication Required
Identity set contains an identity from an allowed domain, but it does not map to a valid username for this connector
```

Help me to solve this, please.

**Comment by animeshbchowdhury** [comment]
Hi @ZFTurbo ,

do you have your globusid or uid set properly? I didn't face this issue before and I got this link which explains the possible problem. 

[https://docs.ccv.brown.edu/globus/getting-started/log-in-with-brown-account](url)

**Comment by ZFTurbo** [comment]
May be it's because I used Google/Orcid ID to Log In. Here is the full log:

```
Command Failed: Error (login)
Endpoint: OpenABC-D: A Large-Scale Dataset For Machine Learning Guided Integrated Circuit Synthesis (ae7b03ad-9e50-472c-9601-ff99054ae47c)
Server: 216.165.13.143:443
Message: Login Failed
---
Details: 530-Login incorrect. : Mapping collection to specified ID failed.
530-GlobusError: v=1 c=LOGIN_DENIED
530-GridFTP-Message: Identity set contains an identity from an allowed domain, but it does not map to a valid username for this connector
530-GridFTP-JSON-Result: {
	"DATA_TYPE": "result#1.0.0",
	"code": "permission_denied",
	"detail": {
		"DATA_TYPE": "invalid_user#1.0.0",
		"usernames": [
			"abc586"
		]
	},
	"has_next_page": false,
	"http_response_code": 403,
	"message": "Identity set contains an identity from an allowed domain, but it does not map to a valid username for this connector"
}
530 End.      
```

May be there is other place where I can download data?

**Comment by animeshbchowdhury** [comment]
Hi @ZFTurbo,

Unfortunately, I was unable to host this last dataset elsewhere. Can you please try downloading it now? There was an issue on our side which we have fixed for syncing the data.

Best,
Animesh

**Comment by ZFTurbo** [comment]
Thank you, now I can download!

**Comment by PiyiHan** [comment]
I am encountering the same problem, could you please tell me how did you solve it?
