### ISSUE TITLE
Can't convert bench file with 'DFF' to graphml file.

### ISSUE THREAD

**Issue by JarvisPei** [NYU-MLDA/OpenABC#6]
Hello. I'm trying to use your 'andAIG2Graphml.py' to generate graphml files from bench files. 

However, I failed when the line in bench file contains 'DFF'. The alert in line 166 of 'andAIG2Graphml.py' is raised:

```
Line contains unknown characters. top.fpu_mul+x1_mul.pre_norm_fmul+u2^exp_out~0_FF_NODE = DFF(n742_1)
```
Please help me to solve it, thanks!

**Comment by animeshbchowdhury** [comment]
Hi @Ed-P,

Currently, I consider the AIGs to be purely combinational designs. Therefore, I use yosys+ABC synthesis flow to extract out the bench file having only the combinational parts (lots of DAGs) and create the grapml.

A simple solution which I recommend is: Write a utility function which performs full scan access to your sequential AIG. In short, replace DFF occurrence by treating inputs to DFF as primary output and output of DFF as primary input.

**Comment by JarvisPei** [comment]
Thank you for your advice @animeshbchowdhury,

If I want to replace the DFF, what command should I use in yosys+ABC? 
Or can I just modify your 'andAIG2Graphml.py', where the 'DFF' is detected and then treat it as ''INPUT'' or ''OUTPUT'' by doing different process. Will it be right?

**Comment by animeshbchowdhury** [comment]
Hi @Ed-P,

I have used OpenROAD project to synthesize which internally use Yosys+abc. You need to just add `write_bench` command to export the combinational bench file in [abc_area.tcl](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/scripts/abc_area.script) script. When you run make synthesis in OpenROAD, this will automatically dump your combinational AIG to user's set path. In this way, it will ensure that  port names of DFF are approrpriately preserved and any optimization applied to AIG will be seamlessly taken back by OpenROAD flow, DFF are stiched and pass on for subsequent flows.

Let me know if anything else you need help with.

**Comment by animeshbchowdhury** [comment]
Hi @Ed-P ,

I recently discovered that there is a command `comb` in ABC which can be used to remove DFF/latches from design and create combinational AIG. You don't explicitly need to convert them from sequential to combinational design.

Best regards,
Animesh

**Comment by JarvisPei** [comment]
Thank you so much! I am even trying to convert the DFF into PI/PO by writing a specific parser. It will be convenient if the `comb` in ABC can remove them.
