### ISSUE TITLE
Missing benchmark data files.

### ISSUE THREAD

**Issue by AntGro** [NYU-MLDA/OpenABC#7]
Hello,

It seems that dft_orig.bench and idft_orig.bench are not in ./bench_openabcd/. Do you know where I could find them, or if I missed something?
Thanks!

**Comment by animeshbchowdhury** [comment]
Hi @AntGro,

I missed uploading the bench files directly into the repository. I have added them now. Please check.

Best regards,
Animesh

**Comment by AntGro** [comment]
Thank you.
