### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by lvchenyangAI** [NYU-MLDA/OpenABC#8]
I‘m a follower of your works and do some research based on openABC-D. We want a pre-trained model for downstream works but the model trained by ourselves is slightly worse than the result in the paper.  Could you provide the pre-trained QoR prediction model(net3)? Thanks a lot.

**Comment by animeshbchowdhury** [comment]
Hi @lvchenyangAI,

Thanks for following up on our work.

Unfortunately, our pre-trained models were kept at /scratch and we didn't keep a backup. However, I can easily train the model our side and share it across. I have some priority for this week. I'll be able to share with you the pre-trained models during first week of April. Will that work?

Best regards,
Animesh

**Comment by lvchenyangAI** [comment]
OK，I really appreciate all the work about openABC-D and your extra assistance provided.

**Comment by animeshbchowdhury** [comment]
Hi @lvchenyangAI ,

Do you need the pre-trained model of Net3 only on Set 1 (i.e. Split Strategy 1) or on all the train-test split?

**Comment by lvchenyangAI** [comment]
***@***.*** Basak Chowdhury
Thank you for your assistance. If you already have a trained model, it is what I need. Also, we are using offline reinforcement learning methods to generate logic synthesis recipes. If you are interested, we can further discuss and exchange ideas.
________________________________
发件人: Animesh Basak Chowdhury ***@***.***>
发送时间: 2023年4月11日 23:42
收件人: NYU-MLDA/OpenABC ***@***.***>
抄送: lvchenyangAI ***@***.***>; Mention ***@***.***>
主题: Re: [NYU-MLDA/OpenABC] Pre-trained model (Issue #8)


Hi @lvchenyangAI<https://github.com/lvchenyangAI> ,

Do you need the pre-trained model of Net3 only on Set 1 (i.e. Split Strategy 1) or on all the train-test split?

―

**Comment by animeshbchowdhury** [comment]
@lvchenyangAI,

Okay I will share across the pre-trained models. 
On our side, we are also working on offline RL strategies for logic synthesis and data distribution issues as well.

Happy to discuss more on this post May deadlines.

**Comment by phyzhenli** [comment]
Hi @animeshbchowdhury,

I’m a follower of your work as well. Have you already uploaded the pre-trained models to the repository?
Thank you very much.

**Comment by animeshbchowdhury** [comment]
Hi @phyzhenli and @lvchenyangAI 

Extremely sorry for not being able to do so due summer paper deadlines during this period.
Allow me some time (preferably this week) I have trained it on SynthNet V1 but SynthNet V2 and V3 are still remaining.
