### ISSUE TITLE
About sequential circuits

### ISSUE THREAD

**Issue by chenxindaaa** [NYU-MLDA/OpenABC#9]
Hello,
I found there are some sequential circuits in the dataset.  ABC will generally synthesize some latches in the AIG. However, the AIG node types defined in this dataset are only [PI, PO, AND].  Could you tell me how to deal with this problem? Did you simply remove the latches from the AIG? 
Best regards

**Comment by animeshbchowdhury** [comment]
Hi @chenxindaaa,

Yes, we do have sequential designs in our dataset. However, we are only extracting out the combinational AIG of the design using Yosys synthesis flow and worked on it using ABC.

Best regards,
Animesh

**Comment by chenxindaaa** [comment]
Thank you so much for your prompt response and for providing me with the information I needed. Besides, I was wondering if you could kindly provide me with more details about the specific commands or steps you used during the Yosys synthesis flow to extract the combinational AIG.

**Comment by animeshbchowdhury** [comment]
Hi @chenxindaaa,

[Openroad ](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/tree/master)provide a hassle-free way of performing synthesis using Yosys. 

Run [`make synth`](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/df9a44242f8474591b0dcdd19c67f059b3d7eebe/flow/Makefile#L380) with designs files at proper location and you will get synthesized version of your design.

Here are the lines where you need to add an extra line of command to extract out the un-optimized combinational AIG of sequential design:

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/df9a44242f8474591b0dcdd19c67f059b3d7eebe/flow/scripts/abc_area.script#L2

Here, add a line: `write <path_to_dump>/design_combinational.aig`

This will dump the unoptimized AIG of your sequential design.

**Comment by chenxindaaa** [comment]
Thanks again for your reply and great work!
